language: java
sudo: true
on:
  branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_fb365c1216b5_key -iv $encrypted_fb365c1216b5_iv -in anuj-ubuntu-keypair.pem.enc -out anuj-ubuntu-keypair.pem -d
- eval "$(ssh-agent -s)"
- pwd
- ls
- echo "$TRAVIS_BUILD_DIR"
- chmod 600 anuj-ubuntu-keypair.pem
- ssh-add anuj-ubuntu-keypair.pem
- chmod +x mvnw
deploy:
  provider: script
  skip_cleanup: true
  script: ls && pwd && cd Travis && cd target && sudo scp -i ../../anuj-ubuntu-keypair.pem  -o StrictHostKeyChecking=no -r `pwd` ubuntu@ec2-34-202-237-229.compute-1.amazonaws.com:/home
jdk:
- openjdk8
script: "./mvnw clean install"
after_success: 
