language: java
sudo: true
true:
  branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_a9de9b3dc3ed_key -iv $encrypted_a9de9b3dc3ed_iv
  -in anuj-ubuntu-keypair.pem.enc -out /tmp/deploy -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy
- ssh-add /tmp/deploy
- chmod +x mvnw
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR root@ec2-34-202-237-229.compute-1.amazonaws.com:home/deploy
jdk:
- openjdk8
script: "./mvnw clean install"
after_success: 
