language: java
sudo: true
branches:
  only:
  - master
jdk:
- openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_fb365c1216b5_key -iv $encrypted_fb365c1216b5_iv -in anuj-ubuntu-keypair.pem.enc -out anuj-ubuntu-keypair.pem -d
- eval "$(ssh-agent -s)"
- pwd
- ls
- echo "$TRAVIS_BUILD_DIR"
- chmod 600 anuj-ubuntu-keypair.pem
- ssh-add anuj-ubuntu-keypair.pem
- chmod +x mvnw
deploy:
  provider: script
  skip_cleanup: true
  script: cd target && sudo scp -i ../anuj-ubuntu-keypair.pem  -o StrictHostKeyChecking=no -r *.jar ubuntu@ec2-34-202-237-229.compute-1.amazonaws.com:/home/Travis
after_deploy:
  script: ssh -i ../anuj-ubuntu-keypair.pem -o StrictHostKeyChecking=no ubuntu@ec2-34-202-237-229.compute-1.amazonaws.com 'cd /home/Travis && ls'
script: "./mvnw clean install"
after_success: 